### ISSUE TITLE
Support `py_modules` in the root (config.yml)

### ISSUE THREAD

**Issue by mapleeit** [jina-ai/executor-normalizer#43]
Now we support: 

```yml
jtype: Executor4
metas:
  py_modules:
    - foo.py
```

We need support this as well:

```yml
jtype: Executor4
py_modules:
  - foo.py
```

We support both in Jina Core. And recommend user to use the 2nd in the documentation bc it's more simple. So we need to add this feature.
